### ISSUE TITLE
Gateway Data Source Status - new error message "Cannot access a disposed object 'SslStream'"

### ISSUE THREAD

**Issue by lbendlin** [migueesc123/PowerBIRESTAPI#95]
This worked fine until very recently.  Might be related to the December 2021 updates?  Will try to narrow it down as to where exactly it happens.  The error is getting thrown despite an existing try ... otherwise ... encapsulation.

Error happens both with GatewayDataSourceStatus and with GETRawData.  So maybe something in the API changed.

Unexpected error: Cannot access a disposed object.
Object name: 'SslStream'.
Details:
    Microsoft.Mashup.Evaluator.Interface.ErrorException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SslProtocol()
   at lambda_method(Closure , Object )
   at Microsoft.Mashup.Engine1.Library.Common.TlsSniffer.GetProtocols(Stream s)
   at Microsoft.Mashup.Engine1.Library.Common.WebRequestFactory.TlsStatistics.GetTlsIndex(String scheme, Stream stream)
   at Microsoft.Mashup.Engine1.Library.Common.WebRequestFactory.TlsStatistics.Record(Uri responseUri, Stream stream)
   at Microsoft.Mashup.Engine1.Library.Common.WebRequestFactory.TlsSniffingWebResponse.GetResponseStream()
   at Microsoft.Mashup.Engine1.Library.Web.CompressionExtensions.GetDecompressedResponseStream(WebResponse response)
   at Microsoft.Mashup.Engine1.Library.Web.HttpResponse.GetResponseStream()
   at Microsoft.Mashup.Engine1.Library.Web.Response.Serialize(Response response)
   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponseCore(ResourceCredentialCollection credentials)
   at Microsoft.Mashup.Engine1.Library.Common.RetryPolicy.Execute[TResult](IEngineHost host, Func`1 func)
   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponse(ResourceCredentialCollection credentials, RetryPolicy retryPolicy, SecurityExceptionCreator securityExceptionCreator, Boolean tokenRefreshed)
   at Microsoft.Mashup.Engine1.Library.Web.WebContentsBinaryValue.GetResponse(Request request)
   at Microsoft.Mashup.Engine1.Library.Web.WebContentsBinaryValue.Open()
   at Microsoft.Mashup.Engine1.Runtime.BinaryValue.OpenText(Encoding encoding)
   at Microsoft.Mashup.Engine1.Library.Json.JsonModule.Json.DocumentFunctionValue.TypedInvoke(Value jsonText, Value encoding)
   at Microsoft.Mashup.Engine1.Runtime.NativeFunctionValue2`3.Invoke(Value arg0, Value arg1)
   at Microsoft.Mashup.Engine1.Language.DebugInstruction.Execute(MembersFrame1& frame)
   at Microsoft.Mashup.Engine1.Language.TryCatchInstruction.Execute(MembersFrame1& frame)
   at Microsoft.Mashup.Engine1.Language.DebugInstruction.Execute(MembersFrame1& frame)
   at Microsoft.Mashup.Engine1.Language.MembersFunctionValue1.Invoke(Value arg0)
   at Microsoft.Mashup.Engine1.Language.MembersFunctionValue0.Invoke()
   at Microsoft.Mashup.Engine1.Language.ListInstruction.RuntimeListValue.Force(Int32 index)
   at Microsoft.Mashup.Engine1.Language.ListInstruction.RuntimeListValue.get_Item(Int32 index)
   at Microsoft.Mashup.Engine1.Runtime.ElementAccessValueReference.get_Value()
   at Microsoft.Mashup.Engine1.Runtime.RecordValue.ReferenceArrayRecordValue.get_Item(Int32 index)
   at Microsoft.Mashup.Engine1.Language.EqualsInstruction.ExecuteCondition(Value frame)
   at Microsoft.Mashup.Engine1.Language.IfInstruction.Execute(Value frame)
   at Microsoft.Mashup.Engine1.Runtime.TransformValueReference.get_Value()
   at Microsoft.Mashup.Engine1.Runtime.RecordValue.ReferenceArrayRecordValue.get_Item(Int32 index)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.<>c__DisplayClass109_0.<WritePreviewFieldValue>b__0()
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.HandleErrors(Action action, Action`1 handler)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.<>c__DisplayClass100_2.<WritePreviewTable>b__2()
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.HandleErrors(Action action, Action`1 handler)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.<>c__DisplayClass100_1.<WritePreviewTable>b__1()
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.HandleErrors(Action action, Action`1 handler)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.HandleErrors(Action action, Action`1 handler)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.WritePreviewTable(IValue value)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.HandleErrors(Action action, Action`1 handler)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.WritePreviewValue(IValue value, Int32 serializeStructuredValueDepth)
   at Microsoft.Mashup.Evaluator.Services.ValueSerializer.SerializePreviewValue(IEngine engine, IValue value, Action`2 rowCountCallback, Nullable`1 options)
   at Microsoft.Mashup.Evaluator.SimpleDocumentEvaluator.ValuePreviewValueSource.TableValuePreviewValueSource.SerializeRows(Int32 count)
   at Microsoft.Mashup.Evaluator.SimpleDocumentEvaluator.ValuePreviewValueSource.TableValuePreviewValueSource.get_SmallValue()
   at Microsoft.Mashup.Evaluator.Interface.TracingPreviewValueSource.get_SmallValue()
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.<>c__DisplayClass0_0.<RunStub>b__0()
   at Microsoft.Mashup.Evaluator.EvaluationHost.ReportExceptions(IHostTrace trace, IEngineHost engineHost, IMessageChannel channel, Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Mashup.Evaluator.EvaluationHost.<>c__DisplayClass14_0.<TryReportException>b__1()
   at Microsoft.Mashup.Common.SafeExceptions.IgnoreSafeExceptions(IEngineHost host, IHostTrace trace, Action action)
   at Microsoft.Mashup.Evaluator.EvaluationHost.TryReportException(IHostTrace trace, IEngineHost engineHost, IMessageChannel channel, Exception exception)
   at Microsoft.Mashup.Evaluator.EvaluationHost.ReportExceptions(IHostTrace trace, IEngineHost engineHost, IMessageChannel channel, Action action)
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.RunStub(IEngineHost engineHost, IMessageChannel channel, Func`1 getPreviewValueSource)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.Service.<>c__DisplayClass12_1`1.<OnBeginGetResult>b__0()
   at Microsoft.Mashup.Evaluator.EvaluationHost.ReportExceptions(IHostTrace trace, IEngineHost engineHost, IMessageChannel channel, Action action)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.Service.OnBeginGetResult[T](IMessageChannel channel, BeginGetResultMessage message, Action`1 action)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.Service.OnBeginGetPreviewValueSource(IMessageChannel channel, BeginGetPreviewValueSourceMessage message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.ChannelMessenger.ChannelMessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.ChannelMessenger.OnMessageWithUnknownChannel(IMessageChannel baseChannel, MessageWithUnknownChannel messageWithUnknownChannel)
   at Microsoft.Mashup.Evaluator.MessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.ChannelMessenger.ChannelMessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.EvaluationHost.Run()
   at Microsoft.Mashup.Container.EvaluationContainerMain.Run(Object args)
   at Microsoft.Mashup.Evaluator.SafeThread2.<>c__DisplayClass9_0.<CreateAction>b__0(Object o)
   at Microsoft.Mashup.Container.EvaluationContainerMain.SafeRun(String[] args)
   at Microsoft.Mashup.Container.EvaluationContainerMain.Main(String[] args)
   --- End of inner exception stack trace ---
   at Microsoft.Mashup.Evaluator.EvaluationHost.OnException(IEngineHost engineHost, IMessageChannel channel, ExceptionMessage message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.ChannelMessenger.ChannelMessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.Interface.IMessageChannelExtensions.WaitFor[T](IMessageChannel channel)
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.PreviewValueSource.WaitFor(Func`1 condition, Boolean disposing)
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.PreviewValueSource.get_Value()
   at Microsoft.Mashup.Evaluator.Interface.TracingPreviewValueSource.get_Value()
   at Microsoft.Mashup.Host.Document.Preview.PreviewEvaluation.<>c__DisplayClass22_0.<StartEvaluation>b__0(EvaluationResult2`1 result)

**Comment by lbendlin** [comment]
Feedback Type:
Frown (Error)

Error Message:
Cannot access a disposed object.
Object name: 'SslStream'.


Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_1.<Main>b__2()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.100.684.0","ModuleName":"","Component":"Microsoft.Mashup.Engine1.Library.Common.TlsSniffer","Error":"System.ObjectDisposedException","MethodDef":"GetProtocols","ErrorOffset":""}


Model Default Mode:
Import

Model Version:
PowerBI_V3


PowerBINonFatalError_ErrorDescription:
Microsoft.Mashup.Host.Document.Evaluation.ErrorEvaluationResult


Formulas to reproduce:  (Commented out #"Added Custom"  line is my current fallback option)


section Section1;

shared #"Gateway Data Sources" = let
    Source = PowerBIRESTAPI.Navigation(),
    Gateways1 = Source{[Key="Gateways"]}[Data],
    GatewayDataSources = Gateways1{[Key="GatewayDataSources"]}[Data],
    #"Added Custom" = Table.AddColumn(GatewayDataSources, "Status", each try Json.Document(PowerBIRESTAPI.GETRawData("/gateways/"&[Gateway ID]&"/datasources/"&[Gateway Datasource ID]&"/status"),65001) otherwise "ok")
    //#"Added Custom" = Table.AddColumn(GatewayDataSources, "Status", each "unknown")
in
    #"Added Custom";

**Comment by migueesc123** [comment]
Hey! I'd encourage you to get in touch with the power bi support team to help you diagnose this issue.

I'm not aware of what that error means.

**Comment by lbendlin** [comment]
@migueesc123 I found the root cause.  Ironically it is your connector.  It turns out that the gateway connection status check fails for connections that use the custom PowerBIRESTAPI connector.  Since that check makes no sense anyway, the remedy is to exclude these connections from the testing.

**Comment by klinejordan** [comment]
Not sure I really understand either, but that gateway status API is flimsy. I've moved on to using the undocumented Power Platform Admin Center APIs. What "testing" are you talking about @lbendlin?

**Comment by lbendlin** [comment]
@klinejordan "testing"  refers to the connection status testing (200 or 400).  Care to elaborate on "the undocumented Power Platform Admin Center APIs"  ?

**Comment by migueesc123** [comment]
Was the gateway throwing the 400 errors? During a refresh? Or during the set up of the scheduled refresh ? 

Do you happen to have any repro steps?

**Comment by albertocaa1317** [comment]
@lbendlin I have this error also.
How you fix it or have you a workaround to retrieve the "datasource status" data?

**Comment by lbendlin** [comment]
Issue is fixed with June 2022 release as promised.

**Comment by lbendlin** [comment]
Microsoft have acknowledged the issue and are planning to fix it in the June 2022 release.On Jun 7, 2022 6:22 AM, Alberto Castro ***@***.***> wrote:
@lbendlin I have this error also.
How you fix it or have you a workaround to retrieve the "datasource status" data?
